// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mir3.Web.Data;

#nullable disable

namespace Mir3.Web.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Mir3.Web.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("AdminUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdminUsers_FailedAttempts_NonNegative", "\"FailedAttempts\" >= 0");

                            t.HasCheckConstraint("CK_AdminUsers_NormalizedUsername_MaxLength", "length(\"NormalizedUsername\") <= 64");

                            t.HasCheckConstraint("CK_AdminUsers_PasswordHash_MaxLength", "length(\"PasswordHash\") <= 512");

                            t.HasCheckConstraint("CK_AdminUsers_Username_MaxLength", "length(\"Username\") <= 64");
                        });
                });

            modelBuilder.Entity("Mir3.Web.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Target");

                    b.ToTable("AuditEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditEntries_Action_MaxLength", "length(\"Action\") <= 128");

                            t.HasCheckConstraint("CK_AuditEntries_Actor_MaxLength", "length(\"Actor\") <= 128");

                            t.HasCheckConstraint("CK_AuditEntries_DetailsJson_MaxLength", "\"DetailsJson\" IS NULL OR length(\"DetailsJson\") <= 4096");

                            t.HasCheckConstraint("CK_AuditEntries_Target_MaxLength", "length(\"Target\") <= 256");
                        });
                });

            modelBuilder.Entity("Mir3.Web.Domain.PortalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoActivateAfterEmailVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PortalSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortalSettings_Singleton_Id", "\"Id\" = 1");

                            t.HasCheckConstraint("CK_PortalSettings_Singleton_Key", "\"Key\" = 'portal'");
                        });
                });

            modelBuilder.Entity("Mir3.Web.Domain.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdminDisabledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailDeliveryAttemptAcquiredUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmailDeliveryAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLastErrorCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GameActivatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InitialEmailDeliveryPending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PendingPasswordHash")
                        .HasMaxLength(36)
                        .HasColumnType("BLOB");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<string>("QueueCommandType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QueueLastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueLastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueuePublicationState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueueRequestId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SourceIpHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerificationExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VerificationTokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("VerificationUsedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("QueueRequestId");

                    b.HasIndex("Status");

                    b.HasIndex("VerificationTokenHash");

                    b.HasIndex("Status", "EmailDeliveryAttemptAcquiredUtc");

                    b.HasIndex("Status", "QueuePublicationState");

                    b.HasIndex("Status", "QueueLastCheckedUtc", "UpdatedUtc", "Id");

                    b.ToTable("Registrations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Registrations_EmailDeliveryAttempt_Ownership", "\"EmailDeliveryAttemptAcquiredUtc\" IS NULL OR \"EmailDeliveryAttemptId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Registrations_EmailLastErrorCode_Value", "\"EmailLastErrorCode\" IS NULL OR \"EmailLastErrorCode\" IN ('smtp-connect', 'smtp-auth', 'smtp-send')");

                            t.HasCheckConstraint("CK_Registrations_Email_MaxLength", "length(\"Email\") <= 320");

                            t.HasCheckConstraint("CK_Registrations_NormalizedEmail_MaxLength", "length(\"NormalizedEmail\") <= 320");

                            t.HasCheckConstraint("CK_Registrations_PasswordHash_Length", "length(\"PasswordHash\") = 36");

                            t.HasCheckConstraint("CK_Registrations_PendingPasswordHash_Length", "\"PendingPasswordHash\" IS NULL OR length(\"PendingPasswordHash\") = 36");

                            t.HasCheckConstraint("CK_Registrations_PreferredLanguage_Value", "\"PreferredLanguage\" IN ('en', 'pl')");

                            t.HasCheckConstraint("CK_Registrations_QueueLastErrorCode_MaxLength", "\"QueueLastErrorCode\" IS NULL OR length(\"QueueLastErrorCode\") <= 64");

                            t.HasCheckConstraint("CK_Registrations_QueuePublicationState_Value", "\"QueuePublicationState\" IS NULL OR \"QueuePublicationState\" IN ('Pending', 'Published', 'Uncertain')");

                            t.HasCheckConstraint("CK_Registrations_SourceIpHash_Length", "length(\"SourceIpHash\") = 32");

                            t.HasCheckConstraint("CK_Registrations_Status_Value", "\"Status\" IN ('PendingEmail', 'AwaitingAdmin', 'QueuePending', 'Active', 'Disabled', 'Failed')");

                            t.HasCheckConstraint("CK_Registrations_VerificationTokenHash_Length", "length(\"VerificationTokenHash\") = 32");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
